apiVersion: v1
kind: Service
metadata:
  name: react-service-nodeport-1
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30003  # NodePort for the first service
