apiVersion: apps/v1
kind: Deployment
metadata:
  name: sts-app
  namespace: Testing
  labels:
    app: sts-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sts-app
  template:
    metadata:
      labels:
        app: sts-app
    spec:
      containers:
      - name: sts-app
        image: imranmik/sts-kube
        ports:
        - containerPort: 8081
