apiVersion: v1
kind: Service
metadata:
  name: sts-service-nodeport-1
spec:
  type: NodePort
  selector:
    app: sts-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30003  # NodePort for the first service
